version: '3'
services:
  app_proxy:
    enviroment:
      APP_HOST: seanapp-handbrake_server_1
      APP_PORT: 5800
  handbrake:
    image: jlesage/handbrake
    ports:
      - "5800:5800"
    volumes:
      - "${APP_DATA_DIR}/HandBrake/config:/config:rw"
      - "${APP_DATA_DIR}/HandBrake/:/storage:ro"
      - "${APP_DATA_DIR}/HandBrake/watch:/watch:rw"
      - "${APP_DATA_DIR}/HandBrake/watch2:/watch2"
      - "${APP_DATA_DIR}/HandBrake/output:/output:rw"