version: "3"
services:
  app_proxy:
    environment:
      APP_HOST: sean-apps-handbrake_server_1
      APP_PORT: 5800
    
  server:
    image: jlesage/handbrake
    ports:
      - "5800:5800"
    volumes:
      - "/mnt/storage/umbrel-docker/data/appdata/HandBrake/config:/config:rw"
      - "/mnt/storage/umbrel-docker/data/appdata/HandBrake/:/storage:ro"
      - "/mnt/storage/umbrel-docker/data/appdata/HandBrake/watch:/watch:rw"
      - "/mnt/storage/umbrel-docker/data/appdata/HandBrake/watch2:/watch2"
      - "/mnt/storage/umbrel-docker/data/appdata/HandBrake/output:/output:rw"
    environment:
      - UMASK=000
      - PGID=1000
      - PUID=1000
      - TZ=America/New_York
